# 飞书应用鉴权配置
auth:
  app_id: "cli_a764f6097a31900d" # "${FEISHU_APP_ID}"           # 建议从环境变量注入
  app_secret: "uYhxXhyoJbmrTiSB4ZzmTb64wxMAwTVM" #"${FEISHU_APP_SECRET}"

tables:
  header_index_row : 1
  header_name_row : 2
  header_type_row : 3
  header_comment_row : 4
  data_start_row : 5